import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { TrendingUpIcon, CheckCircleIcon, ShieldIcon, SparklesIcon, ChevronRightIcon } from '../../../components/icons.tsx';

/**
 * Executive Briefing Component
 * Shows high-level value delivered to the client since the last session.
 * "What have we done for you lately?"
 */

import { mockDataService } from '../../../services/mockDataService';
import { SessionSummary } from '../../../types';

interface ExecutiveBriefingProps {
    hideWrapper?: boolean;
}

export const ExecutiveBriefing: React.FC<ExecutiveBriefingProps> = ({ hideWrapper = false }) => {
    const [isExpanded, setIsExpanded] = useState(true);
    const [summary, setSummary] = useState<SessionSummary | undefined>(undefined);

    React.useEffect(() => {
        setSummary(mockDataService.getLatestSessionSummary());
    }, []);

    if (!summary) {
        return (
            <div className="bg-white/90 backdrop-blur-md rounded-2xl border border-white/20 shadow-sm overflow-hidden mb-6 p-6 text-center">
                <p className="text-slate-500 italic">No executive briefings available yet. Complete a session to generate insights.</p>
            </div>
        );
    }

    // Transform SessionSummary to display format if needed
    // Assuming SessionSummary has strategy, execution, risks matching the UI
    // If not, we might need to map it. 
    // Step 69 showed SessionSummary has detailed fields.

    // Transform SessionSummary to flat list for the widget
    const items = [
        ...(summary.strategy?.items || []).map(text => ({ type: 'strategy', text, impact: summary.strategy?.impact } as const)),
        ...(summary.execution?.items || []).map(text => ({ type: 'execution', text, impact: summary.execution?.impact } as const)),
        ...(summary.risks?.items || []).map(text => ({ type: 'risk', text, impact: summary.risks?.impact } as const))
    ];

    const content = (
        <div className="flex flex-col">
            <div className="px-5 py-3 space-y-2 border-t border-outline/10">
                {items.map((item, i) => (
                    <div key={i} className="flex items-center justify-between p-2 rounded-lg hover:bg-surface-variant/30 transition-colors group">
                        <div className="flex items-center gap-3">
                            <span className={`
                                w-2 h-2 rounded-full
                                ${item.type === 'strategy' ? 'bg-blue-500' : ''}
                                ${item.type === 'execution' ? 'bg-green-500' : ''}
                                ${item.type === 'risk' ? 'bg-orange-500' : ''}
                            `} />
                            <div className="flex flex-col">
                                <span className="text-base font-medium text-slate-900 group-hover:text-primary transition-colors">{item.text}</span>
                                {item.impact && (
                                    <span className="text-xs text-slate-500 uppercase tracking-widest mt-0.5">
                                        Impact: <span className="font-bold text-slate-800">{item.impact}</span>
                                    </span>
                                )}
                            </div>
                        </div>

                        <span className={`
                            text-[9px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-full opacity-0 group-hover:opacity-100 transition-opacity
                            ${item.type === 'strategy' ? 'bg-blue-100 text-blue-700' : ''}
                            ${item.type === 'execution' ? 'bg-green-100 text-green-700' : ''}
                            ${item.type === 'risk' ? 'bg-orange-100 text-orange-700' : ''}
                        `}>
                            {item.type}
                        </span>
                    </div>
                ))}
            </div>

            {/* Footer Action */}
            <div className="bg-primary/5 px-5 py-2 flex justify-between items-center text-xs">
                <span className="text-slate-600 font-medium italic">Generated by Pinnacle AI Analysis</span>
                <Link to="/executive-briefings" className="font-bold text-primary hover:text-secondary uppercase tracking-wide">View Full Report</Link>
            </div>
        </div>
    );

    if (hideWrapper) return content;

    return (
        <div className="bg-white/90 backdrop-blur-md rounded-2xl border border-white/20 shadow-sm overflow-hidden mb-4">
            {/* Header */}
            <div
                className="px-5 py-3 bg-gradient-to-r from-surface-variant/50 to-transparent flex items-center justify-between cursor-pointer"
                onClick={() => setIsExpanded(!isExpanded)}
            >
                <div className="flex items-center gap-2.5">
                    <div className="p-2 bg-primary/10 rounded-lg text-primary">
                        <SparklesIcon className="w-5 h-5" />
                    </div>
                    <div>
                        <h3 className="font-serif text-lg font-bold text-primary">Executive Briefing</h3>
                        <p className="text-xs text-slate-600 font-medium">Since your last session</p>
                    </div>
                </div>
                <div className="flex items-center gap-3">
                    <Link
                        to="/executive-briefings"
                        onClick={(e) => e.stopPropagation()}
                        className="text-xs font-bold text-slate-400 hover:text-primary uppercase tracking-wider flex items-center gap-1 px-2 py-1 rounded hover:bg-black/5 transition-all"
                    >
                        History
                    </Link>
                    <ChevronRightIcon className={`w-5 h-5 text-slate-500 transition-transform ${isExpanded ? 'rotate-90' : ''}`} />
                </div>
            </div>

            {/* Content */}
            <div className={`transition-all duration-300 ease-in-out ${isExpanded ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'}`}>
                {content}
            </div>
        </div>
    );
};
