import {
    UsersIcon,
    LightbulbIcon,
    TrophyIcon,
    CalendarIcon,
    HeartHandshakeIcon,
    StarIcon,
    BriefcaseIcon,
    TrendingUpIcon,
    DollarSignIcon,
    LayoutGridIcon,
    SparklesIcon,
} from "../../components/icons";
import { VisionSection } from "./types";

export const DEFAULT_SECTIONS: VisionSection[] = [
    {
        id: "who-we-are",
        title: "Who WE ARE In",
        subtitle: "",
        icon: UsersIcon,
        bgColor: "bg-rose-50",
        borderColor: "border-rose-200",
        content: "",
        hasDatePicker: true,
    },
    {
        id: "differentiators",
        title: "Our DIFFERENTIATORS",
        subtitle: "",
        icon: SparklesIcon,
        bgColor: "bg-purple-50",
        borderColor: "border-purple-200",
        content: "",
    },
    {
        id: "3-year-goals",
        title: "Our 3 Year Goals (BHAG)",
        subtitle: "Big Hairy Audacious Goal",
        icon: TrendingUpIcon,
        bgColor: "bg-amber-50",
        borderColor: "border-amber-200",
        content: "",
    },
    {
        id: "what-we-do",
        title: "WHAT We Do",
        subtitle: "",
        icon: BriefcaseIcon,
        bgColor: "bg-yellow-50",
        borderColor: "border-yellow-200",
        content: "",
    },
    {
        id: "our-core",
        title: "Our CORE",
        subtitle: "",
        icon: StarIcon,
        bgColor: "bg-blue-50",
        borderColor: "border-blue-200",
        content: "",
    },
    {
        id: "our-signature-process",
        title: "Our SIGNATURE Process",
        subtitle: "",
        icon: LayoutGridIcon,
        bgColor: "bg-indigo-50",
        borderColor: "border-indigo-200",
        content: "",
    },
    {
        id: "marketing-strategy",
        title: "MARKETING STRATEGY",
        subtitle: "",
        icon: SparklesIcon,
        bgColor: "bg-cyan-50",
        borderColor: "border-cyan-200",
        content: "",
    },
    {
        id: "customer-experience",
        title: "Our CUSTOMER EXPERIENCE",
        subtitle: "Who We Serve and How We Serve Them",
        icon: HeartHandshakeIcon,
        bgColor: "bg-teal-50",
        borderColor: "border-teal-200",
        content: "",
    },
    {
        id: "employees",
        title: "EMPLOYEES",
        subtitle: "",
        icon: UsersIcon,
        bgColor: "bg-green-50",
        borderColor: "border-green-200",
        content: "",
    },
    {
        id: "operational-excellence",
        title: "Our OPERATIONAL EXCELLENCE",
        subtitle: "",
        icon: TrophyIcon,
        bgColor: "bg-lime-50",
        borderColor: "border-lime-200",
        content: "",
    },
    {
        id: "our-team",
        title: "Our TEAM",
        subtitle: "",
        icon: UsersIcon,
        bgColor: "bg-orange-50",
        borderColor: "border-orange-200",
        content: "",
    },
    {
        id: "profits",
        title: "Our PROFITS (Q1 | Mid Year | End Yr.)",
        subtitle: "",
        icon: DollarSignIcon,
        bgColor: "bg-pink-50",
        borderColor: "border-pink-200",
        content: "",
    },
    {
        id: "our-focus",
        title: "OUR FOCUS",
        subtitle: "",
        icon: LightbulbIcon,
        bgColor: "bg-gray-50",
        borderColor: "border-gray-200",
        content: "",
    },
    {
        id: "annual-priorities",
        title: "ANNUAL PRIORITIES",
        subtitle: "",
        icon: CalendarIcon,
        bgColor: "bg-slate-50",
        borderColor: "border-slate-200",
        content: "",
    },
];
